In [1]:
import pandas as pd

# Load the dataset from the URL
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df = pd.read_csv(url)

# Display the first few rows to understand the structure
df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

## Challenge 1: Understanding the data

In [2]:
# Get the dimensions of the dataset
rows, columns = df.shape
print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")

Number of rows: 4008
Number of columns: 11

In [4]:
# To check the data types of each column
df.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [5]:
# To get unique value counts for each column
unique_values = df.nunique()
print(unique_values)

Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

In [6]:
# To identify categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns
print(categorical_columns)

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Number of Open Complaints', 'Policy Type', 'Vehicle Class'],
      dtype='object')

In [7]:
# Describe the unique value of each categorical column
for column in categorical_columns:
    print(f"\ncolumn'{column}' unique values:")
    print(df[column].unique())

column'Customer' unique values:
['RB50392' 'QZ44356' 'AI49188' ... 'CW49887' 'MY31220' nan]

column'ST' unique values:
['Washington' 'Arizona' 'Nevada' 'California' 'Oregon' 'Cali' 'AZ' 'WA'
 nan]

column'GENDER' unique values:
[nan 'F' 'M' 'Femal' 'Male' 'female']

column'Education' unique values:
['Master' 'Bachelor' 'High School or Below' 'College' 'Bachelors' 'Doctor'
 nan]

column'Customer Lifetime Value' unique values:
[nan '697953.59%' '1288743.17%' ... '2031499.76%' '323912.47%'
 '899704.02%']

column'Number of Open Complaints' unique values:
['1/0/00' '1/2/00' '1/1/00' '1/3/00' '1/5/00' '1/4/00' nan]

column'Policy Type' unique values:
['Personal Auto' 'Corporate Auto' 'Special Auto' nan]

column'Vehicle Class' unique values:
['Four-Door Car' 'Two-Door Car' 'SUV' 'Luxury SUV' 'Sports Car'
 'Luxury Car' nan]

In [8]:
# Summary Statistics for Numerical columns
numerical_summary = df.describe()
print(numerical_summary)

             Income  Monthly Premium Auto  Total Claim Amount
count   1071.000000           1071.000000         1071.000000
mean   39295.701214            193.234360          404.986909
std    30469.427060           1601.190369          293.027260
min        0.000000             61.000000            0.382107
25%    14072.000000             68.000000          202.157702
50%    36234.000000             83.000000          354.729129
75%    64631.000000            109.500000          532.800000
max    99960.000000          35354.000000         2893.239678

In [9]:
# Summary statistics for categorical colums
categorical_summary = df[categorical_columns].describe()
print(categorical_summary)

       Customer      ST GENDER Education Customer Lifetime Value  \
count      1071    1071    954      1071                    1068
unique     1071       8      5         6                    1027
top     RB50392  Oregon      F  Bachelor              445811.34%
freq          1     320    457       324                       4

       Number of Open Complaints    Policy Type  Vehicle Class
count                       1071           1071           1071
unique                         6              3              6
top                       1/0/00  Personal Auto  Four-Door Car
freq                         830            780            576

## Challenge 2: Analyzing the Data

In [11]:
# Exercise 1: Top 5 least common costumer locations
least_common_locations = df['ST'].value_counts().tail(5)
print(least_common_locations)

ST
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [12]:
# Exercise 2: Total Number of Policies Sold per Type
policy_counts = df['Policy Type'].value_counts()
print(policy_counts)

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [13]:
# Exercise 3: Comparing Average Income for Policy Types
# Separate dataframes for Personal Auto and Corporate Auto policies
personal_auto = df.loc[df['Policy Type'] == 'Personal Auto']
corporate_auto = df.loc[df['Policy Type'] == 'Corporate Auto']

# Calculate average income for each
avg_income_personal = personal_auto['Income'].mean()
avg_income_corporate = corporate_auto['Income'].mean()

print(f"Average income for Personal Auto: ${avg_income_personal:.2f}")
print(f"Average income for Corporate Auto: ${avg_income_corporate:.2f}")

Average income for Personal Auto: $38180.70
Average income for Corporate Auto: $41390.31

In [14]:
# Exercise 4: Identifying High Policy Claim Amount Customers
# Calculate the 75th percentile for Total Claim Amount
claim_75th_percentile = df['Total Claim Amount'].quantile(0.75)

# Filter customers with Total Claim Amount above the 75th percentile
high_claim_customers = df[df['Total Claim Amount'] > claim_75th_percentile]

# Display summary statistics for these high claim customers
high_claim_summary = high_claim_customers.describe()
high_claim_summary

             Income  Monthly Premium Auto  Total Claim Amount
count    264.000000            264.000000          264.000000
mean   23677.344697            165.193182          782.228263
std    27013.483721            623.930992          292.751640
min        0.000000             63.000000          537.600000
25%        0.000000             99.000000          606.521741
50%    18807.000000            114.000000          679.597985
75%    42423.750000            133.250000          851.400000
max    99316.000000          10202.000000         2893.239678